### ISSUE TITLE
Question: Does this library handle alterations on regular columns used by a db-view?

### ISSUE THREAD

**Issue by jchubber** [BezBartek/django-db-views#10]
Thank you very much for publishing this library. I'm considering adding it to our application, and I have a question about whether it supports a particular use case:

If a _regular_ django migration wants to change a db column which is used by a database view, postgres will normally reject the change with the error `cannot alter type of a column used by a view or rule`. In this `django-db-views` library, is such a conflict detected, and if so, how is it addressed? For example, does the [ViewMigrationAutoDetector](https://github.com/BezBartek/django-db-views/blob/master/django_db_views/autodetector.py#L15) understand when those situations arise? I've reviewed the autodetector code, but I'm not yet fully understanding how it works so I thought to double-check with those watching this repo on github. 

Thank you again for sharing this library!

**Comment by BezBartek** [comment]
Hello,

Thank you for your comment.
Currently, there is no conflict detection. 
You will get an exception from Postgres when you try to run the migration.

It is maybe something that I should add in the near future
