### ISSUE TITLE
Migrations generated with 0.0.9 aren't compatible with 0.1.0

### ISSUE THREAD

**Issue by joshmcarthur** [BezBartek/django-db-views#12]
Maybe this is my fault for using a 0.0.x release of a library ;-)

The per-engine support released in 0.1.0 is not compatible with migrations generated in 0.0.9, as these migrations do not define an `engine` parameter. This means that in the migration commands, `self.view_engine` is set to `None`, and [the if condition in the forward and backward migrations](https://github.com/BezBartek/django-db-views/blob/4225d358ef28176c1611c68c5e2ae236892a66fb/django_db_views/migration_functions.py#L18) can never evaluate to True. 

This means that confusingly, the migrations successfully run, but make no changes. I _think_ that assigning `self.db_engine` to `self.view_engine` if `engine` is not defined would be sufficient to fix this, since this is in line with the behaviour expressed in the README:

> If you do not pass in an engine and have a str or callable the engine will be defaulted to the default database defined in django.settings

This statement is currently implemented as part of the [migration generator](https://github.com/BezBartek/django-db-views/blob/4225d358ef28176c1611c68c5e2ae236892a66fb/django_db_views/autodetector.py#L135), but should probably also be reflected in the actual migration functions.

**Comment by BezBartek** [comment]
@joshmcarthur 
No this is not your fault, I should catch that. 
Thank you for your comment!
I'm gonna repair it this weekend

**Comment by BezBartek** [comment]
Fixed, today I published version 0.1.1 on PyPi
Thank you once again :)
