### ISSUE TITLE
What is view definitions?

### ISSUE THREAD

**Issue by saileshkush95** [BezBartek/django-db-views#13]
I'm trying to use this package, But I'm little bit confused about view definition, Can i use raw sql query , If how?

For example Suppose I want to create virtual table for users, So now how can i define virtual table so that i can include first_name last_name and last_login from user table in virtual table.

**Comment by BezBartek** [comment]
```
class UsersView(DBView):
      last_name = models.CharField(...)
      last_login = models.DateTimeField(...)
      first_name = models.CharField(...)
      view_definition = """
            write your raw query here.
            Your query has to return fields named: id, last_name, last_login, first_name. 
      """
```
Also, you can use ORM to write a view definition
```
class UsersView(DBView):
      last_name = models.CharField(...)
      last_login = models.DateTimeField(...)
      first_name = models.CharField(...)

      view_definition = lambda: str(User.objects.all().annotate(last_login=...).query) 

```
Also, you can find an example in the readme. 

Please let me know if this solves your problem

**Comment by saileshkush95** [comment]
Thank you this one solves my problems
