### ISSUE TITLE
Materialized views support

### ISSUE THREAD

**Issue by kyrylo-omelchenko-ddi** [BezBartek/django-db-views#14]
Hi! Thanks for you work on the lib!

It would be great to have an option to define a `mateiralized view` instead of regular ones. A Meta option would be nice.
```python
class Meta:
    materialized = True #False by default
```

**Comment by BezBartek** [comment]
@kyrylo-omelchenko-ddi 
Hello!,
Yes, adding materialized views is a great idea. I had an idea to add it from the beginning, but I hadn't enough free time to do so, that's why I put it on hold. I will add it as soon as I find a free time for it. 
Be aware of updates and thank you for your comment

**Comment by BezBartek** [comment]
@kyrylo-omelchenko-ddi 
It took some time :D but it is Done
