### ISSUE TITLE
Is managed=False required for DBViews?

### ISSUE THREAD

**Issue by andrew-cybsafe** [BezBartek/django-db-views#15]
We're recently started to use this package, but we're experiencing an issue when the normal Django migrations process is trying to create a table where the view already exists. Of course this fails as you can't create a table with the same name as the view.

Will adding managed=False fix this? And will adding this cause makeviewmigrations stop working for changes to the view?

**Comment by BezBartek** [comment]
Hello!
Yes, you have to set `manager=False`. 
makeviewmigrations will work normally. I probably should add an assert, which checks during makeviewmigrations command that DB views have manage=False.

**Comment by andrew-cybsafe** [comment]
Thanks for confirming. Yes, adding that check would be good. Also, I documentation update would be great.

**Comment by BezBartek** [comment]
Check is added
