### ISSUE TITLE
Question: can the schema identifiers be excluded from the views' SQL code?

### ISSUE THREAD

**Issue by mwfrost** [BezBartek/django-db-views#17]
In some cases, the MySQL views installed by `django-db-views` include the schema name in the table references, even if the `code=` argument did not use fully-qualified table names. Is there a way to avoid this? I'd like to be able to dump the view code and load it into a different schema without having to grep the schema name out.

**Comment by BezBartek** [comment]
Do you use `db_table` explicitly?

For example:
```python
class MyView(DBView):
     ...
     class Meta:
          managed = False
          abstract = True
          db_table = "my_view_name"
```
