### ISSUE TITLE
Creating migrations 

### ISSUE THREAD

**Issue by ketrab100** [BezBartek/django-db-views#22]
I have a problem generating new migrations. 
When I use command `makeviewmigrations`  everything goes well., but during database migration I receive error `django.db.utils.ProgrammingError: column "widget" does not exist`. Problem is in queryset - `filter=Q( column_name="widget" )`. Writing something like a `filter=Q( column_name="'widget'" )` solves the problem but passing raw string can lead to sql injection.

**Comment by BezBartek** [comment]
@ketrab100 
Hello

Are you able to provide me more details? Like your model definition

It seems that you didn't create a column to which you refer to in your view migration query. 
Are you run migrations in correct order (see dependency in migration files)?

**Comment by ketrab100** [comment]
Problem is in `QuerySet.query.__str__()` function. It doesn't return valid sql query https://code.djangoproject.com/ticket/17741. Problem is solved by replacing __str__ function by `connection.cursor().mogrify(*queryset.query.sql_with_params()).decode()`

**Comment by BezBartek** [comment]
@ketrab100 
Thank you for pointing that, 
I will add a proper note about that in documentation this week
