### ISSUE TITLE
Is this package really compatible with Python 3.8 ?

### ISSUE THREAD

**Issue by lajus** [BezBartek/django-db-views#38]
When i run `$./manage.py makeviewmigrations`, i get:

```
File "/opt/venv/rls_venv/lib/python3.8/site-packages/django_db_views/autodetector.py", line 332, in ViewMigrationAutoDetector
    def _get_view_identifiers_from_operation(self, operation) -> tuple[str, str]:
TypeError: 'type' object is not subscriptable
```

and ChatGPT informs me that:
> The issue arises because in Python 3.8, the ability to use square brackets ([]) for subscripting types like tuple directly in type hints was not yet available. This feature, called PEP 585—which allows built-in collection types like tuple, list, dict, etc., to be subscripted directly—was introduced in Python 3.9.

If it is true, you should update the README.

Regards,
Jonathan

**Comment by lajus** [comment]
`pip install django-db-views==0.1.6` seems to solve this Python 3.8 compatibility issue.

**Comment by BezBartek** [comment]
Hello, Yes, I will remove 3.8 from supported list in recent versions. 
Thank you for pointing that.
