### ISSUE TITLE
Different Engines for Local / Dev / Prod

### ISSUE THREAD

**Issue by Skylude** [BezBartek/django-db-views#9]
This is likely not a common issue but we have a project where we utilize multiple backend engines for our database. Locally we run postgresql and in production we utilize MSSQL. It would be really nice to be able to define different versions of SQL and have that dynamically executed in the migrate command.

**Comment by BezBartek** [comment]
It seems not to be a hard thing to add, Thank you for your thought. 
If you add it, then I will review and merge your change, otherwise, I will add it myself as fast as I find a free day
